PUT http://localhost:3000/admin/users/authorized/548c70af-676c-4248-a90d-3830d6f022c6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzODFlMjNlNy1iNjFhLTRkNzYtYWI2YS0xNzNlNTAwNDg5OWQiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NzI3MDc1NTQsImV4cCI6MTc3MjcxMTE1NH0.boA_KQZ_ecVl8k0QJ-BEJSl21L0bqxNGZrwv-b3uH4U

{
    "role": "ALUMNI"
}