GET http://localhost:3000/students/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmYjczN2YzYi05NTk1LTQ1ZWYtOTU5Ni03MGRiNmYxNzBlYTMiLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc3MjcxNjg0NSwiZXhwIjoxNzcyNzIwNDQ1fQ.apGT-JnGVa53vz_vTFVPFT84YTWbeTKm3bUlo4QrfO8
Content-Type: application/json
