//Get users who are registered
GET http://localhost:3000/admin/users/authorized
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ODc0YWQ3Yy0wN2Q2LTQwNDMtYTVkNC03MGExZDc4Yzc1NDQiLCJyb2xlIjoiQURNSU4iLCJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3NzQwMTIwNDUsImV4cCI6MTc3NDAxNTY0NX0.JdTor7D5Iji7DGgaRa9aBO13PhFGy98GjizZ-ai6yYU