//Get users who are registered
GET http://localhost:3000/admin/users/authorized
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzODFlMjNlNy1iNjFhLTRkNzYtYWI2YS0xNzNlNTAwNDg5OWQiLCJyb2xlIjoiQURNSU4iLCJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3NzMzMDY1ODYsImV4cCI6MTc3MzMxMDE4Nn0.kCwx50yrGeEfhTRCuPyyXz4rGMe_9yE-dKwSeh7tf3I