POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "gzh4n7@tr.pte.hu",
    "password": "gzh4n7",
    "firstName": "Ranjan",
    "lastName": "Shankar"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "bnerc9@tr.pte.hu",
    "password": "bnerc9",
    "firstName": "Bharat",
    "lastName": "Nair"
}