POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "fbn7ym@tr.pte.hu",
    "password": "fbn7ym",
    "firstName": "Vasundhara",
    "lastName": "Ravikumar"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json  

{
    "email": "h1ckbo@tr.pte.hu",
    "password": "h1ckbo",
    "firstName": "Vivian",
    "lastName": "Murathimi"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "ztyboc@tr.pte.hu",
    "password": "ztyboc",
    "firstName": "Lakshmi",
    "lastName": "Ravikumar"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "PMNRY6@tr.pte.hu",
    "password": "PMNRY6",
    "firstName": "Anna",
    "lastName": "Andrews"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "AK4WJQ@tr.pte.hu",
    "password": "ak4wjq",
    "firstName": "John",
    "lastName": "Smith"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "E1WU52@tr.pte.hu",
    "password": "e1wu52",
    "firstName": "Emily",
    "lastName": "Cooper"
}



