POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "fbn7ym@tr.pte.hu",
    "password": "fbn7ym",
    "firstName": "Vasundhara",
    "lastName": "Ravikumar"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json  

{
    "email": "h1ckbo@tr.pte.hu",
    "password": "h1ckbo",
    "firstName": "Vivian",
    "lastName": "Murathimi"
}