# =================================
# 2️⃣ Upload Profile Picture
# =================================
PUT http://localhost:3000/students/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmYjczN2YzYi05NTk1LTQ1ZWYtOTU5Ni03MGRiNmYxNzBlYTMiLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc3MjcxNzIwMCwiZXhwIjoxNzcyNzIwODAwfQ.wPEtBopMnsXW8VfK93PgP19HrZ_z2wE7NmZrPUtXg8U
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="profilePicture"; filename="profile.png"
Content-Type: image/png

< /home/vasu/Downloads/Profile_pics/profile.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--