//This file is used to check if : 
//email exists in AuthorizedUser
//Ensure isUsed = false
// Hash password
//Create User
//Create role-specific profile (Student/Alumni/etc.)
//Mark AuthorizedUser.isUsed = true
//Return user
//This use case should depend only on:
//UserRepository
//AuthorizedUserRepository
//PasswordHasher

import { UserRepository } from 'src/domain/repositories/user.repository';
import { AuthorizedUserRepository } from 'src/domain/repositories/authorized-user.repository';
import { PasswordHasher } from 'src/domain/services/password-hasher';
import { Role } from 'src/domain/entities/user.entity';

interface RegisterUserRequest {
  email: string;
  password: string;
  role: string; // e.g., 'student', 'alumni', etc.
}

export class RegisterUserUseCase {
  constructor(
    private userRepository: UserRepository,
    private authorizedUserRepository: AuthorizedUserRepository,
    private passwordHasher: PasswordHasher
  ) {}

  async execute(request: RegisterUserRequest) {
    const { email, password, role } = request;

    // Check if email exists in AuthorizedUser
    const authorizedUser = await this.authorizedUserRepository.findByEmail(email);
    if (!authorizedUser) {
      throw new Error('Email not authorized for registration');
    }

    // Ensure isUsed = false
    if (authorizedUser.isUsed) {
      throw new Error('Email has already been used for registration');
    }

    // Hash password
    const hashedPassword = await this.passwordHasher.hash(password);

    // Convert string role to Role enum
    const roleEnum = (Role as any)[role as keyof typeof Role];
    if (!roleEnum) {
      throw new Error('Invalid role');
    }

    // Create User
    // You may want to collect firstName and lastName from the request or set defaults
    const firstName = '';
    const lastName = '';
    const fullName = () => `${firstName} ${lastName}`.trim();

    // id is typically generated by the repository/database, so set it as undefined or let the repository handle it
    const user = await this.userRepository.create({
      id: '',
      email,
      password: hashedPassword,
      role: roleEnum,
      firstName,
      lastName,
      fullName,
    });

    // Mark AuthorizedUser.isUsed = true
    authorizedUser.isUsed = true;
    await this.authorizedUserRepository.update(authorizedUser);

    // Return user
    return user;
  }
}