GET http://localhost:3000/professors/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNWEwNmM2OS0wMGJlLTQ4ODItYTFkMi03ZWE2ZTVlOGRlMDIiLCJyb2xlIjoiUFJPRkVTU09SIiwiaWF0IjoxNzcyNzk3NzI3LCJleHAiOjE3NzI4MDEzMjd9.FVcn7a5V2sFLDJeuRnaw1MmXbFkbVYPSJth5bH-Fbho
